//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeMergerCS {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class omSet : global::System.Configuration.ApplicationSettingsBase {
        
        private static omSet defaultInstance = ((omSet)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new omSet())));
        
        public static omSet Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>B3</string>
  <string>B4</string>
  <string>B5</string>
  <string>B6</string>
  <string>B7</string>
  <string>B8</string>
  <string>B9</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ListBoxSetting {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ListBoxSetting"]));
            }
            set {
                this["ListBoxSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MainRangeSetting {
            get {
                return ((string)(this["MainRangeSetting"]));
            }
            set {
                this["MainRangeSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MainRangeStartSetting {
            get {
                return ((string)(this["MainRangeStartSetting"]));
            }
            set {
                this["MainRangeStartSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MainRangeEndSetting {
            get {
                return ((string)(this["MainRangeEndSetting"]));
            }
            set {
                this["MainRangeEndSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MainRangeDataTag {
            get {
                return ((string)(this["MainRangeDataTag"]));
            }
            set {
                this["MainRangeDataTag"] = value;
            }
        }
    }
}
